name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: your-account-id.dkr.ecr.your-region.amazonaws.com

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 851725266600.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: hello-world-nodejs
        IMAGE_TAG: latest
      run: |
        docker build -t 851725266600.dkr.ecr.ap-south-1.amazonaws.com/hello-world-nodejs .
        docker push 851725266600.dkr.ecr.ap-south-1.amazonaws.com/hello-world-nodejs

    - name: Download Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1
